Lecture summaries - LEIC41N
===========================
:toc: auto

Lecture 1 - 2025-02-18 - 1.5h
-----------------------------
* Course introduction
    ** link:https://isel.pt/sites/default/files/FUC_202425_1637.pdf[_Ficha de Unidade Curricular_].
    ** Goals
    ** Programme
        *** 16 weeks, including one week without lectures and some national holidays.
        *** See link:calendar.adoc[Calendar].
    ** Evaluation
        *** See link:course-evaluation.adoc[Course evaluation].
    ** Resources
        *** See link:resources.adoc[Resources].
    ** Tooling
        *** See link:tools.adoc[Tools].

Lecture 2 - 2025-02-21 - 3.0h
-----------------------------
* Introduction to concurrent programming and its challenges
    ** A motivating example - a TCP server
        *** Handling a single client at a time.
        *** Handling multiple clients simultaneously.
    ** Thread creation in the JVM.
        *** Available mechanisms.
        *** Consequences and hazards.
    ** Threading hazards.
        *** E.g. Lost increments.
        *** E.g. Lost insertions.

* Exercises
    ** Setting up the development environment and making sure it is working correctly - see link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/exercises/environment-setup.adoc[Environment setup].

* Resources:
    ** link:https://github.com/isel-leic-pc/s2425v-li41d-li41n/blob/main/code/jvm/src/main/kotlin/pt/isel/pc/sketches41n/apps/MyFirstTcpServer.kt[`MyFirstTcpServer`] developed during the lecture.
    ** link:https://github.com/pmhsfelix/course-jvm-concurrency/tree/main/code/jvm/src/main/kotlin/org/pedrofelix/concurrency/course/apps/tcpserver[Different versions for the TCP server].
    ** link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/lecture-notes/a-motivating-example-tcp-server.adoc[A motivating example].
    ** link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/lecture-notes/threading-data-hazards.adoc[Threading data hazards].

Lecture 3 - 2025-02-25 - 1.5h
-----------------------------

* A model of how threads are implemented.
    ** Multiple processors using shared memory.
    ** Thread shared memory areas and thread exclusive memory areas.
    ** The concept of context and of context switch.
    ** Time multiplexing of M threads on N processors, when M is greater than N.

* The _uthreads_ user-space multithreading system.
    ** Thread data structures - stack and descriptor.
    ** Suspending and resuming _uthreads_ - the `context_switch` function.

* Resources
    ** link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/lecture-notes/platform-threads-introduction.adoc[Platform threads].
    ** link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/lecture-notes/uthreads.adoc[_uthreads_ - User Mode Cooperative Threads].

Lecture 4 - 2025-02-28 - 3.0h
-----------------------------

* The _uthreads_ user-space multithreading system (continuation)
    ** Creating and terminating _uthreads_.
    ** The _uthreads_ system data structures, namely the ready queue.
    ** The _uthreads_ scheduling function.

* Adding control synchronization to the _uthreads_ system.
    ** Busy-waiting vs non-busy waiting.
    ** Adding a list of _joiners_ to each thread descriptor.
    ** Kernel-style (execution delegation).

* Adding I/O based control synchronization to the _uthreads_ system.
    ** Socket operations in the Linux Operating System.
    ** Non-blocking operation mode and the _epoll_ API.
    ** Changing the _uthreads_ system to support non-busy I/O control synchronization using _epoll_.

* Exercises
    ** _uthreads_ - see link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/exercises/uthreads.adoc[_uthreads_ exercises].

* Resources
    ** link:https://github.com/pmhsfelix/course-jvm-concurrency/blob/main/docs/lecture-notes/uthreads.adoc[_uthreads_ - User Mode Cooperative Threads].
